name: FGC DEV Regression Tests API

on:
  # Disparar manualmente
  workflow_dispatch:

  # Disparar automaticamente toda sexta-feira às 19:00 UTC
  schedule:
    - cron: "0 19 * * 5"

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Newman
      - name: Install Newman
        run: npm install -g newman

      # Listar os arquivos no repositório para verificação
      - name: List Files
        run: ls -R

      # Executar a coleção Postman
      - name: Run Postman Collection
        run: |
          newman run qa_dev_fgc_contribuições.postman_collection.json \
            -r cli \
            || true


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
