name: FGC DEV Regression Tests API

on:
  # Disparar manualmente
  workflow_dispatch:

  # Disparar automaticamente toda sexta-feira às 19:00 UTC
  schedule:
    - cron: "0 19 * * 5"

  # Disparar automaticamente em cada push para a branch main
  push:
    branches:
      - main

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Newman
      - name: Install Newman
        run: npm install -g newman

      # Listar os arquivos no repositório para verificação
      - name: List Files
        run: ls -R

      # Executar a coleção Postman
      - name: Run Postman Collection
        id: run_tests
        run: |
          newman run qa_dev_fgc_contribuições.postman_collection.json -r cli || echo "TEST_FAILED"

      # Enviar e-mail após a execução
      - name: Send Email Notification
        if: always() # Sempre executa, independente do sucesso ou falha
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: |
            FGC DEV Regression Tests: ${{ job.status }}
          to: jean.villete@gft.com,tamires.reis@gft.com
          from: github-actions@example.com
          body: |
            **FGC DEV Regression Tests Execution**

            - **Status:** ${{ job.status }}
            - **Branch:** ${{ github.ref }}
            - **Repository:** ${{ github.repository }}
            - **Workflow URL:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            **Logs e Detalhes:**
            O teste foi executado no GitHub Actions. Verifique os resultados no link acima.




      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
