name: FGC QA Regression Tests API

on:
  # Disparar manualmente
  workflow_dispatch:

  # Disparar automaticamente toda sexta-feira às 19:00 UTC
  schedule:
    - cron: "0 19 * * 5"

  # Disparar automaticamente em cada push para a branch main
  push:
    branches:
      - main

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # Fazer o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Newman
      - name: Install Newman
        run: npm install -g newman

      # Listar os arquivos no repositório para verificação
      - name: List Files
        run: ls -R

      # Executar a coleção Postman
      - name: Run Postman Collection
        id: run_tests
        run: |
          newman run qa_fgc_contribuições.postman_collection.json -r cli
      # Exibir mensagem em caso de falha
      - name: Log Failure
        if: failure()  # Executa apenas se houver falha nos passos anteriores
        run: |
          echo "===================================="
          echo "🚨 Pipeline Failed!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Verifique os logs em:"
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "===================================="

