name: Secret
on:
  workflow_dispatch
jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: checkou code
        uses: actions/checkout@v4
      - name: verificar segredo
        run: | 
          echo SMTP_PASSWORD
          echo ${{secrets.SMTP_PASSWORD}} | sed 's/./& /g'
          echo SMTP_USERNAME
          echo ${{secrets.SMTP_USERNAME}} | sed 's/./& /g'
